### ISSUE TITLE
Error: data/mods//MST_Extra_Mod-master

### ISSUE THREAD

**Issue by LeonARS** [chaosvolt/MST_Extra_Mod#17]
DEBUG    : Error: data/mods//MST_Extra_Mod-master/MST_Extra/chargen/start_locations.json: line 3:30: must specify either id or abstract

[
  {
    "type": "start_location",
                             ^
    "id": "swamp",
    "name": "Swamp",
    "terrain": [ "forest_water" ],

 
 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 696

CDDA version 0.D

**Comment by chaosvolt** [comment]
You're using a very old stable build, I'd recommend using 0.E experimental builds given how much has changed since then. They're close to putting 0.F out and when they do I'll set aside a release for that, and I'm planning to make a Bright Nights release soon-ish, see their repo for details on that fork: https://github.com/cataclysmbnteam/Cataclysm-BN
