### ISSUE TITLE
to 0.E-3 and beyond !

### ISSUE THREAD

**Issue by Moltenhead** [chaosvolt/MST_Extra_Mod#20]
Hi. I've just tested your mod in last master release and had to made those changes to make it work :

- `covers` Enum ids are now needing to be in UPSCALE form
- `chemistry` skill is now incorporated within `cooking` skill - `chemistry` skill has been removed
- `stone_chopper` item has disapeared (can't be overwritten)
- `category_groups` is not used anymore - and trigger errors if trying to generate new ones
- `construction` requires a `description` argument
- `name` `str_sp` parameter isn't accepted anymore - changed to `str` by default
- `HAMMER_SOFT` quality is now `HAMMER`
- `PUNCH` quality has been removed
- `stone_flaking` item has been removed - error on recipes dependencies (I removed any that was present)
- `construction_category` now needs to get previously declared (added `WINDOWS` category)

I can make a temporary fork if you want with the rough changes I made - or just send you my version. I suppose it needs a little more tweaks to get back to what you wanted this mode to be, but at least it can get loaded after those quick tweaks.

Edit : Sent you an invitation on a private repo, you can check the pull request there.

**Comment by chaosvolt** [comment]
I'm sorry, which build are you testing the master branch of this mod on? Because that sounds like you're using the master version of MST Extra on 0.E Stable, not recent experimental builds.

I'll test the mod on a recent build later when I get back from some errands and fix anything I find, but I'm guessing the 0.E stable release may need updating? I haven't really updated stable releases that often, especially since by now we're probably a year away from 0.F and the last stable has been out for a good while.

**Comment by Moltenhead** [comment]
Don't really know which build it is, last 0.E-3 main version of CDDA released on the main dl page.
And no worries. I can play the game with the tweaked version of your mod I just supposed it could help if you'd like to update it. Didn't knew some new major update was one the way soon.
Anyway, there's a fork I made that you can access if you want, if it helps : good, if you don't need it : at least its working for me. :)

**Comment by chaosvolt** [comment]
Yeah, you're using 0.E stable release, not experimental versions.
For CDDA that can be found here: https://github.com/CleverRaven/Cataclysm-DDA/releases
For CBN, the releases are here: https://github.com/cataclysmbnteam/Cataclysm-BN/releases
